import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("../src/main.jsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
const viteConfig = readFileSync(new URL("../vite.config.js", import.meta.url), "utf8");

assert.match(source, /crypto\.randomUUID\(\)/, "submissions should generate a requestId");
assert.match(source, /useState\("start"\)/, "app should open on the start page first");
assert.match(source, /function StartPage/, "start page component should exist");
assert.match(source, /<h1>Athena<\/h1>/, "main product title should be Athena");
assert.match(source, /Systems Simplified/, "brand tagline should be rendered");
assert.match(source, /<p className="brand-tagline">Systems Simplified<\/p>/, "start page should show the tagline directly below title");
assert.doesNotMatch(source, /Requirement Change Impact Analysis/, "dashboard subtitle should not be shown");
assert.doesNotMatch(source, /Human-in-the-loop requirement change intelligence/, "start page subtitle should not be shown");
assert.match(source, /Upload requirement artefact/, "start page upload control should be shown");
assert.match(source, /Describe requirement change/, "start page change input should be shown");
assert.match(source, /Analyse Impact/, "start page analyse button should be shown");
assert.match(styles, /\.start-page[\s\S]*#f8fbff/, "start page should use a light background");
assert.match(styles, /\.start-card[\s\S]*background: rgba\(255, 255, 255/, "start card should be light themed");
assert.match(source, /Please upload and ingest a requirement artefact first\./, "missing artefact validation should be shown");
assert.match(source, /Please describe the requirement change\./, "missing change text validation should be shown");
assert.match(source, /latestRequestIdRef\.current = requestId/, "latest requestId should be tracked");
assert.match(source, /setGraph\(initialGraph\)/, "old graph should be cleared before a new result");
assert.match(source, /setImpactAnalysis\(null\)/, "old AI analysis should be cleared before a new result");
assert.match(source, /setMode\("dashboard"\)/, "successful accepted results should transition to dashboard");
assert.match(source, /\/api\/graph\/impact-from-change/, "frontend should call impact-from-change");
assert.match(source, /\/api\/graph\/impact-analysis/, "frontend should call the backend-only LLM analysis endpoint");
assert.match(source, /\/api\/graph\/ingest/, "start page should call the existing ingest endpoint");
assert.match(source, /function resolveApiBaseUrl/, "frontend should resolve API base URL at runtime");
assert.match(source, /\|\| ""/, "frontend should default to same-origin API calls");
assert.doesNotMatch(source, /localhost:8000/, "frontend should not default browser API calls to localhost:8000");
assert.match(viteConfig, /VITE_API_PROXY_TARGET \|\| "http:\/\/backend:8000"/, "Docker frontend should proxy API calls to the backend service");
assert.match(viteConfig, /"\/api"[\s\S]*target: proxyTarget/, "Vite should proxy API requests through the frontend origin");
assert.match(source, /JSON\.stringify\(\{ changeText, depth: 2, requestId \}\)/, "requestId should be sent to the backend");
assert.match(source, /payload\.requestId !== latestRequestIdRef\.current/, "late responses should be ignored");
assert.match(source, /requestId !== latestRequestIdRef\.current/, "late AI analysis responses should be ignored");
assert.match(source, /key=\{graphVersion\}/, "graph component should remount for accepted graph versions");
assert.doesNotMatch(source, /candidate\.score|score\.toFixed|Candidates & Ontology|Search Results/, "candidate scores/rankings should not be rendered");
assert.match(source, /No matching requirement found\./, "empty results should show a clear no-match message");
assert.match(source, /SkeletonStack/, "AI analysis loading state should use skeleton cards");
assert.match(source, /AI analysis could not be generated for this graph\. Please review the impact map manually\./, "AI failure should render a clean non-technical message");
assert.match(source, /AI suggestion - engineer approval required/, "human-in-the-loop advisory badge should be displayed");
assert.match(source, /AI-generated suggestions\. Engineer review and approval required\./, "static human-in-the-loop footer should be rendered");
assert.match(source, /Analysis Summary/, "analysis summary should be shown");
assert.match(source, /Ripple Effects/, "ripple effects should be shown when present");
assert.match(source, /Suggested Next Steps/, "suggested next steps should be shown");
assert.match(source, /const MAX_RIPPLE_EFFECTS = 3/, "frontend should allow up to 3 ripple effects");
assert.match(source, /rippleEffects: \(analysis\.rippleEffects \|\| \[\]\)\.slice\(0, MAX_RIPPLE_EFFECTS\)\.map/, "frontend should render up to 3 ripple effects from backend");
assert.doesNotMatch(source, /slice\(0,\s*1\)|rippleEffects\[0\]|maxRippleEffects\s*=\s*1/, "frontend should not clip ripple effects to one item");
assert.match(source, /AI reviewed \$1/, "provider-specific review wording should be normalized to AI reviewed REQ-XXX");
assert.match(source, /sanitizeAnalysis/, "AI analysis text should be cleaned before display");
assert.doesNotMatch(source, /Generated by Ollama|Generated by OpenAI|Rule-based fallback|providerLabel|provider-label|fallback-notice|Local LLM unavailable|Engineering Review Checklist|Assumptions and Limitations|humanInTheLoopNotice|errorDetails|invalid JSON|errors\.pydantic/, "AI panel should not expose provider/model/checklist/assumption/error details");
assert.match(source, /<ImpactGraph key=\{graphVersion\} graph=\{graph\}/, "graph visualization should still receive impacted nodes and edges");
assert.match(source, /New Analysis/, "dashboard should include New Analysis button");
assert.match(source, /Re-run Analysis/, "dashboard should include Re-run Analysis button");
assert.doesNotMatch(source, /ImpactSummaryStrip|SummaryMetric|Impacted Nodes|Critical Items/, "knowledge graph summary metrics strip should not be rendered");
assert.doesNotMatch(styles, /impact-summary-strip|summary-metric/, "knowledge graph summary metrics strip styles should not remain");
assert.match(source, /System \/ Subsystem/, "legend should show readable subsystem label");
assert.match(source, /Verification \/ Test Case/, "legend should show readable test label");
assert.match(source, /graph-node-details-title/, "node details panel should use larger title styling");
assert.match(source, /function graphLayoutOptions/, "graph layout should use dynamic spacing options");
assert.match(source, /idealEdgeLength: largeGraph \? 220 : mediumGraph \? 190 : 160/, "large Cytoscape graphs should use longer edge spacing");
assert.match(source, /nodeRepulsion: largeGraph \? 15000 : mediumGraph \? 12000 : 9000/, "large Cytoscape graphs should use stronger node repulsion");
assert.match(source, /numIter: largeGraph \? 2000 : mediumGraph \? 1700 : 1500/, "large Cytoscape graphs should settle with more iterations");
assert.match(source, /Fit to View/, "graph should include a fit-to-view control");
assert.match(source, /Open Full Screen/, "graph should include a full-screen control");
assert.match(source, /Exit Full Screen/, "full-screen graph should include an exit control");
assert.match(source, /graph-stage-fullscreen/, "full-screen graph mode should use a modal-style overlay class");
assert.match(source, /function resizeAndFitGraph/, "graph should centralize resize and fit behavior");
assert.match(source, /cy\.resize\(\)/, "graph should resize Cytoscape after container size changes");
assert.match(source, /cy\.fit\(undefined, padding\)/, "graph should fit back into its current container");
assert.match(source, /cy\.center\(\)/, "graph should center after resizing");
assert.match(source, /window\.setTimeout\(run, 300\)/, "graph should refit after full-screen exit layout settles");
assert.match(source, /window\.addEventListener\("resize", handleResize\)/, "graph should respond to browser resize events");
assert.doesNotMatch(source, /Reset Layout/, "reset-layout control should be removed");
assert.match(source, /logo-fallback/, "fallback text logo should be supported if image assets are missing");
assert.doesNotMatch(source, /<h3>Impacted Nodes<\/h3>|<h3>Connected Relationships<\/h3>|Affected Node Summary|<OntologyPanel/, "dashboard should not show removed summary sections");
assert.match(styles, /graph-node-details-title[\s\S]*font-size: 20px/, "node details title should use larger text");
assert.match(styles, /graph-node-details-meta[\s\S]*font-size: 16px/, "node details metadata should use larger text");
assert.match(source, /element\.description \? <span className="graph-node-details-description">\{element\.description\}<\/span> : null/, "node details panel should render node descriptions");
assert.match(styles, /\.middle-panel[\s\S]*overflow-y: auto/, "knowledge graph panel should scroll vertically instead of clipping details");
assert.doesNotMatch(styles, /\.middle-panel[\s\S]{0,180}overflow: hidden/, "knowledge graph panel should not hide node details overflow");
assert.match(styles, /\.graph-canvas[\s\S]*min-height: 560px/, "embedded graph canvas should leave room for node details");
assert.match(styles, /\.graph-stage[\s\S]*height: clamp\(500px, calc\(100vh - 310px\), 650px\)/, "embedded graph stage should use responsive height that leaves details visible");
assert.match(styles, /\.graph-node-details[\s\S]*flex-shrink: 0/, "node details panel should not shrink below its content");
assert.match(styles, /\.graph-node-details[\s\S]*overflow: visible/, "node details panel text should not be clipped");
assert.match(styles, /\.graph-controls/, "graph controls should be styled");
assert.match(styles, /\.graph-stage-fullscreen[\s\S]*position: fixed/, "full-screen graph should use fixed overlay styling");

console.log("frontend behavior checks passed");
