import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("../src/main.jsx", import.meta.url), "utf8");

assert.match(source, /crypto\.randomUUID\(\)/, "submissions should generate a requestId");
assert.match(source, /latestRequestIdRef\.current = requestId/, "latest requestId should be tracked");
assert.match(source, /setGraph\(\{ nodes: \[\], edges: \[\] \}\)/, "old graph should be cleared before a new result");
assert.match(source, /setImpactAnalysis\(null\)/, "old AI analysis should be cleared before a new result");
assert.match(source, /\/api\/graph\/impact-from-change/, "frontend should call impact-from-change");
assert.match(source, /\/api\/graph\/impact-analysis/, "frontend should call the backend-only LLM analysis endpoint");
assert.match(source, /JSON\.stringify\(\{ changeText, depth: 2, requestId \}\)/, "requestId should be sent to the backend");
assert.match(source, /payload\.requestId !== latestRequestIdRef\.current/, "late responses should be ignored");
assert.match(source, /requestId !== latestRequestIdRef\.current/, "late AI analysis responses should be ignored");
assert.match(source, /key=\{graphVersion\}/, "graph component should remount for accepted graph versions");
assert.doesNotMatch(source, /candidate\.score|score\.toFixed|Candidates & Ontology|Search Results/, "candidate scores/rankings should not be rendered");
assert.match(source, /No matching requirement found\./, "empty results should show a clear no-match message");
assert.match(source, /Generating local AI impact analysis\. First run may take longer while the model loads\.\.\./, "local AI analysis loading state should mention first-run model loading");
assert.match(source, /AI analysis could not be generated for this graph\. Please review the impact map manually\./, "AI failure should render a clean non-technical message");
assert.match(source, /AI suggestion - engineer approval required/, "human-in-the-loop advisory badge should be displayed");
assert.match(source, /AI-generated suggestions\. Engineer review and approval required\./, "static human-in-the-loop footer should be rendered");
assert.match(source, /Analysis Summary/, "analysis summary should be shown");
assert.match(source, /Ripple Effects/, "ripple effects should be shown when present");
assert.match(source, /Suggested Next Steps/, "suggested next steps should be shown");
assert.doesNotMatch(source, /Generated by Ollama|Generated by OpenAI|Rule-based fallback|providerLabel|provider-label|fallback-notice|Local LLM unavailable|Engineering Review Checklist|Assumptions and Limitations|humanInTheLoopNotice|errorDetails|invalid JSON|errors\.pydantic/, "AI panel should not expose provider/model/checklist/assumption/error details");
assert.match(source, /<ImpactGraph key=\{graphVersion\} graph=\{graph\}/, "graph visualization should still receive impacted nodes and edges");
assert.doesNotMatch(source, /<h3>Impacted Nodes<\/h3>|<h3>Connected Relationships<\/h3>|Affected Node Summary|<OntologyPanel/, "right panel should only show selected requirement and AI analysis sections");

console.log("frontend behavior checks passed");
